### mensaje de bienvenida
GET https://api-arkhamhorror-dev.up.railway.app/

### Retorna el número de visitas totales a la app
GET https://api-arkhamhorror-dev.up.railway.app/visitas

### Suma 1 al contador de visitas
POST https://api-arkhamhorror-dev.up.railway.app/visitas

### Trae la lista de LOGS
GET https://api-arkhamhorror-dev.up.railway.app/logs
